Adding recorder deactivation option
GreenSurvivors/GreenMinigames pull request #28
Opened 2023-12-11 19:56 UTC by joshi1999

To accomplish a minigame, which you only use once (or only one day) and the building and mining progress is valuable after the game.

2023-12-15 06:35 UTC, Schpammer approved these changes

2024-01-04 18:50 UTC, FireInstall commented
rebased onto dev

2024-01-11 12:51 UTC, FireInstall requested changes
Bitte noch die RegenRegions und FloorDegens richtig arbeiten lassen.
Auf die Einstellung sollte statt dessen im BasicRecorder getestet werden um Veränderungen von Spielern auszuklammern.

2024-01-11 12:51 UTC, FireInstall commented on Minigames/src/main/java/au/com/mineauz/minigames/blockRecorder/RecorderData.java
This will do for our event, but how about leaving regen regions out of this config and renaming it to "recordPlayers" or "activateDefaultRecorder"?
If you create a regenRegion you would expect it to function, wouldn't you?

2024-01-11 12:51 UTC, FireInstall commented on Regions/src/main/java/au/com/mineauz/minigamesregions/conditions/MatchTeamCondition.java
Thumbs up for this fix

2024-02-24 11:51 UTC, joshi1999 commented on Minigames/src/main/java/au/com/mineauz/minigames/blockRecorder/RecorderData.java
Jep, I would. xD

2024-02-24 12:41 UTC, FireInstall approved these changes
Nice one! Thanks!

2024-02-25 11:10 UTC, joshi1999 commented
I just couldn't decide whether to rename it or not, but the self documentating code is probably the best argument ^^

2024-02-25 16:54 UTC, FireInstall commented
Perfection. Nice!

2024-02-25 21:42 UTC, merged